export const cardMarker = '\uF200';
export const emoji_ids = {
    "\uE288": "minecraft:soul_campfire",
    "\uE289": "minecraft:soul_lantern",
    "\uE28A": "minecraft:soul_torch",
    "\uE28B": "minecraft:crimson_fungus",
    "\uE28C": "minecraft:warped_fungus",
    "\uE28D": "minecraft:weeping_vines",
    "\uE28E": "minecraft:twisting_vines",
    
    "\uE290": "minecraft:acacia_boat",
    "\uE291": "minecraft:birch_boat",
    "\uE292": "minecraft:dark_oak_boat",
    "\uE293": "minecraft:jungle_boat",
    "\uE294": "minecraft:oak_boat",
    "\uE295": "minecraft:spruce_boat",

    "\uE296": "minecraft:acacia_door",
    "\uE297": "minecraft:birch_door",
    "\uE298": "minecraft:dark_oak_door",
    "\uE299": "minecraft:jungle_door",
    "\uE29A": "minecraft:wooden_door",
    "\uE29B": "minecraft:spruce_door",
    "\uE29C": "minecraft:iron_door",
    "\uE29D": "minecraft:crimson_door",
    "\uE29E": "minecraft:warped_door",
    
    "\uE2A2": "minecraft:acacia_sign",
    "\uE2A3": "minecraft:birch_sign",
    "\uE2A4": "minecraft:dark_oak_sign",
    "\uE2A5": "minecraft:jungle_sign",
    "\uE2A6": "minecraft:oak_sign",
    "\uE2A7": "minecraft:spruce_sign",
    "\uE2A8": "minecraft:crimson_sign",
    "\uE2A9": "minecraft:warped_sign",

    "\uE2AA": { "id": "minecraft:sapling", "data": 0 },
    "\uE2AB": { "id": "minecraft:sapling", "data": 1 },
    "\uE2AC": { "id": "minecraft:sapling", "data": 2 },
    "\uE2AD": { "id": "minecraft:sapling", "data": 3 },
    "\uE2AE": { "id": "minecraft:sapling", "data": 4 },
    "\uE2AF": { "id": "minecraft:sapling", "data": 5 },

    "\uE2B0": { "id": "minecraft:red_flower", "data": 0 },
    "\uE2B1": { "id": "minecraft:red_flower", "data": 1 },
    "\uE2B2": { "id": "minecraft:red_flower", "data": 2 },
    "\uE2B3": { "id": "minecraft:red_flower", "data": 3 },
    "\uE2B4": { "id": "minecraft:red_flower", "data": 4 },
    "\uE2B5": { "id": "minecraft:red_flower", "data": 5 },
    "\uE2B6": { "id": "minecraft:red_flower", "data": 6 },
    "\uE2B7": { "id": "minecraft:red_flower", "data": 7 },
    "\uE2B8": { "id": "minecraft:red_flower", "data": 8 },
    "\uE2B9": { "id": "minecraft:red_flower", "data": 9 },
    "\uE2BA": { "id": "minecraft:red_flower", "data": 10 },
    "\uE2BB": "minecraft:yellow_flower",
    "\uE2BC": { "id": "minecraft:double_plant", "data": 0 },
    "\uE2BD": { "id": "minecraft:double_plant", "data": 1 },
    "\uE2BE": { "id": "minecraft:double_plant", "data": 4 },
    "\uE2BF": { "id": "minecraft:double_plant", "data": 5 },
    
    "\uE2D0": { "id": "minecraft:bed", "data": 0 },
    "\uE2D1": { "id": "minecraft:bed", "data": 1 },
    "\uE2D2": { "id": "minecraft:bed", "data": 2 },
    "\uE2D3": { "id": "minecraft:bed", "data": 3 },
    "\uE2D4": { "id": "minecraft:bed", "data": 4 },
    "\uE2D5": { "id": "minecraft:bed", "data": 5 },
    "\uE2D6": { "id": "minecraft:bed", "data": 6 },
    "\uE2D7": { "id": "minecraft:bed", "data": 7 },
    "\uE2D8": { "id": "minecraft:bed", "data": 8 },
    "\uE2D9": { "id": "minecraft:bed", "data": 9 },
    "\uE2DA": { "id": "minecraft:bed", "data": 10 },
    "\uE2DB": { "id": "minecraft:bed", "data": 11 },
    "\uE2DC": { "id": "minecraft:bed", "data": 12 },
    "\uE2DD": { "id": "minecraft:bed", "data": 13 },
    "\uE2DE": { "id": "minecraft:bed", "data": 14 },
    "\uE2DF": { "id": "minecraft:bed", "data": 15 },
    
    "\uE2EF": "minecraft:candle",
    "\uE2F0": "minecraft:white_candle",
    "\uE2F1": "minecraft:orange_candle",
    "\uE2F2": "minecraft:magenta_candle",
    "\uE2F3": "minecraft:light_blue_candle",
    "\uE2F4": "minecraft:yellow_candle",
    "\uE2F5": "minecraft:lime_candle",
    "\uE2F6": "minecraft:pink_candle",
    "\uE2F7": "minecraft:gray_candle",
    "\uE2F8": "minecraft:light_gray_candle",
    "\uE2F9": "minecraft:cyan_candle",
    "\uE2FA": "minecraft:purple_candle",
    "\uE2FB": "minecraft:blue_candle",
    "\uE2FC": "minecraft:brown_candle",
    "\uE2FD": "minecraft:green_candle",
    "\uE2FE": "minecraft:red_candle",
    "\uE2FF": "minecraft:black_candle",

    "\uE308": "minecraft:activator_rail",
    "\uE309": "minecraft:amethyst_shard",
    "\uE30A": "minecraft:apple",
    "\uE30B": "minecraft:armor_stand",
    "\uE30C": "minecraft:arrow",
    "\uE30D": "minecraft:axolotl_bucket",
    "\uE30E": "minecraft:baked_potato",
    "\uE30F": "minecraft:bamboo",
    "\uE310": "minecraft:beef",
    "\uE311": "minecraft:beetroot",
    "\uE312": "minecraft:beetroot_seeds",
    "\uE313": "minecraft:beetroot_soup",
    "\uE314": "minecraft:bell",
    "\uE315": "minecraft:black_dye",
    "\uE316": "minecraft:blaze_powder",
    "\uE317": "minecraft:blaze_rod",
    "\uE318": "minecraft:blue_dye",
    "\uE319": "minecraft:bone",
    "\uE31A": "minecraft:bone_meal",
    "\uE31B": "minecraft:book",
    "\uE31C": "minecraft:bow",
    "\uE31D": "minecraft:bowl",
    "\uE31E": "minecraft:bread",
    "\uE31F": "minecraft:brewing_stand",
    "\uE320": "minecraft:brick",
    "\uE321": "minecraft:brown_dye",
    "\uE322": "minecraft:brown_mushroom",
    "\uE323": "minecraft:bucket",
    "\uE324": "minecraft:cake",
    "\uE325": "minecraft:campfire",
    "\uE326": "minecraft:carrot",
    "\uE327": "minecraft:carrot_on_a_stick",
    "\uE328": "minecraft:cauldron",
    "\uE329": "minecraft:chain",
    "\uE32A": "minecraft:chainmail_boots",
    "\uE32B": "minecraft:chainmail_chestplate",
    "\uE32C": "minecraft:chainmail_helmet",
    "\uE32D": "minecraft:chainmail_leggings",
    "\uE32E": "minecraft:charcoal",
    "\uE32F": "minecraft:chest_minecart",
    "\uE330": "minecraft:chicken",
    "\uE331": "minecraft:chorus_fruit",
    "\uE332": "minecraft:clay_ball",
    "\uE333": "minecraft:clock",
    "\uE334": "minecraft:coal",
    "\uE335": "minecraft:cocoa_beans",
    "\uE336": "minecraft:cod",
    "\uE337": "minecraft:cod_bucket",
    "\uE338": "minecraft:comparator",
    "\uE339": "minecraft:compass",
    "\uE33A": "minecraft:cooked_beef",
    "\uE33B": "minecraft:cooked_chicken",
    "\uE33C": "minecraft:cooked_cod",
    "\uE33D": "minecraft:cooked_mutton",
    "\uE33E": "minecraft:cooked_porkchop",
    "\uE33F": "minecraft:cooked_rabbit",
    "\uE340": "minecraft:cooked_salmon",
    "\uE341": "minecraft:cookie",
    "\uE342": "minecraft:copper_ingot",
    "\uE343": "minecraft:crossbow",
    "\uE344": "minecraft:cyan_dye",
    "\uE345": "minecraft:detector_rail",
    "\uE346": "minecraft:diamond",
    "\uE347": "minecraft:diamond_axe",
    "\uE348": "minecraft:diamond_boots",
    "\uE349": "minecraft:diamond_chestplate",
    "\uE34A": "minecraft:diamond_helmet",
    "\uE34B": "minecraft:diamond_hoe",
    "\uE34C": "minecraft:diamond_horse_armor",
    "\uE34D": "minecraft:diamond_leggings",
    "\uE34E": "minecraft:diamond_pickaxe",
    "\uE34F": "minecraft:diamond_shovel",
    "\uE350": "minecraft:diamond_sword",
    "\uE351": "minecraft:dried_kelp",
    "\uE352": "minecraft:egg",
    "\uE353": "minecraft:elytra",
    "\uE354": "minecraft:emerald",
    "\uE355": "minecraft:enchanted_book",
    "\uE356": "minecraft:ender_eye",
    "\uE357": "minecraft:ender_pearl",
    "\uE358": "minecraft:end_crystal",
    "\uE359": "minecraft:experience_bottle",
    "\uE35A": "minecraft:feather",
    "\uE35B": "minecraft:fermented_spider_eye",
    "\uE35C": "minecraft:firework_rocket",
    "\uE35D": "minecraft:fire_charge",
    "\uE35E": "minecraft:fishing_rod",
    "\uE35F": "minecraft:flint",
    "\uE360": "minecraft:flint_and_steel",
    "\uE361": "minecraft:flower_pot",
    "\uE362": "minecraft:frame",
    "\uE363": "minecraft:ghast_tear",
    "\uE364": "minecraft:glass_bottle",
    "\uE365": "minecraft:glistering_melon_slice",
    "\uE366": "minecraft:glowstone_dust",
    "\uE367": "minecraft:glow_berries",
    "\uE368": "minecraft:glow_frame",
    "\uE369": "minecraft:glow_ink_sac",
    "\uE36A": "minecraft:golden_apple",
    "\uE36B": "minecraft:golden_axe",
    "\uE36C": "minecraft:golden_boots",
    "\uE36D": "minecraft:golden_carrot",
    "\uE36E": "minecraft:golden_chestplate",
    "\uE36F": "minecraft:golden_helmet",
    "\uE370": "minecraft:golden_hoe",
    "\uE371": "minecraft:golden_horse_armor",
    "\uE372": "minecraft:golden_leggings",
    "\uE373": "minecraft:golden_pickaxe",
    "\uE374": "minecraft:golden_rail",
    "\uE375": "minecraft:golden_shovel",
    "\uE376": "minecraft:golden_sword",
    "\uE377": "minecraft:gold_ingot",
    "\uE378": "minecraft:gold_nugget",
    "\uE379": "minecraft:gray_dye",
    "\uE37A": "minecraft:green_dye",
    "\uE37B": "minecraft:gunpowder",
    "\uE37C": "minecraft:honeycomb",
    "\uE37D": "minecraft:honey_bottle",
    "\uE37E": "minecraft:hopper",
    "\uE37F": "minecraft:hopper_minecart",
    "\uE380": "minecraft:ink_sac",
    "\uE381": "minecraft:iron_axe",
    "\uE382": "minecraft:iron_boots",
    "\uE383": "minecraft:iron_chestplate",
    "\uE384": "minecraft:iron_helmet",
    "\uE385": "minecraft:iron_hoe",
    "\uE386": "minecraft:iron_horse_armor",
    "\uE387": "minecraft:iron_ingot",
    "\uE388": "minecraft:iron_leggings",
    "\uE389": "minecraft:iron_nugget",
    "\uE38A": "minecraft:iron_pickaxe",
    "\uE38B": "minecraft:iron_shovel",
    "\uE38C": "minecraft:iron_sword",
    "\uE38D": "minecraft:kelp",
    "\uE38E": "minecraft:lantern",
    "\uE38F": "minecraft:lapis_lazuli",
    "\uE390": "minecraft:lava_bucket",
    "\uE391": "minecraft:lead",
    "\uE392": "minecraft:leather",
    "\uE393": "minecraft:leather_boots",
    "\uE394": "minecraft:leather_chestplate",
    "\uE395": "minecraft:leather_helmet",
    "\uE396": "minecraft:leather_horse_armor",
    "\uE397": "minecraft:leather_leggings",
    "\uE398": "minecraft:lever",
    "\uE399": "minecraft:light_blue_dye",
    "\uE39A": "minecraft:light_gray_dye",
    "\uE39B": "minecraft:lime_dye",
    "\uE39C": "minecraft:magenta_dye",
    "\uE39D": "minecraft:magma_cream",
    "\uE39E": "minecraft:melon_seeds",
    "\uE39F": "minecraft:melon_slice",
    "\uE3A0": "minecraft:milk_bucket",
    "\uE3A1": "minecraft:minecart",
    "\uE3A2": "minecraft:mushroom_stew",
    "\uE3A3": "minecraft:mutton",
    "\uE3A4": "minecraft:name_tag",
    "\uE3A5": "minecraft:nautilus_shell",
    "\uE3A6": "minecraft:netherbrick",
    "\uE3A7": "minecraft:netherite_axe",
    "\uE3A8": "minecraft:netherite_boots",
    "\uE3A9": "minecraft:netherite_chestplate",
    "\uE3AA": "minecraft:netherite_helmet",
    "\uE3AB": "minecraft:netherite_hoe",
    "\uE3AC": "minecraft:netherite_ingot",
    "\uE3AD": "minecraft:netherite_leggings",
    "\uE3AE": "minecraft:netherite_pickaxe",
    "\uE3AF": "minecraft:netherite_scrap",
    "\uE3B0": "minecraft:netherite_shovel",
    "\uE3B1": "minecraft:netherite_sword",
    "\uE3B2": "minecraft:nether_wart",
    "\uE3B3": "minecraft:orange_dye",
    "\uE3B4": "minecraft:painting",
    "\uE3B5": "minecraft:paper",
    "\uE3B6": "minecraft:phantom_membrane",
    "\uE3B7": "minecraft:pink_dye",
    "\uE3B8": "minecraft:pointed_dripstone",
    "\uE3B9": "minecraft:poisonous_potato",
    "\uE3BA": "minecraft:popped_chorus_fruit",
    "\uE3BB": "minecraft:porkchop",
    "\uE3BC": "minecraft:potato",
    "\uE3BD": "minecraft:powder_snow_bucket",
    "\uE3BE": "minecraft:prismarine_crystals",
    "\uE3BF": "minecraft:prismarine_shard",
    "\uE3C0": "minecraft:pufferfish",
    "\uE3C1": "minecraft:pufferfish_bucket",
    "\uE3C2": "minecraft:pumpkin_pie",
    "\uE3C3": "minecraft:pumpkin_seeds",
    "\uE3C4": "minecraft:purple_dye",
    "\uE3C5": "minecraft:quartz",
    "\uE3C6": "minecraft:rabbit",
    "\uE3C7": "minecraft:rabbit_foot",
    "\uE3C8": "minecraft:rabbit_hide",
    "\uE3C9": "minecraft:rabbit_stew",
    "\uE3CA": "minecraft:rail",
    "\uE3CB": "minecraft:raw_copper",
    "\uE3CC": "minecraft:raw_gold",
    "\uE3CD": "minecraft:raw_iron",
    "\uE3CE": "minecraft:redstone",
    "\uE3CF": "minecraft:redstone_torch",
    "\uE3D0": "minecraft:red_dye",
    "\uE3D1": "minecraft:red_mushroom",
    "\uE3D2": "minecraft:sugar_cane",
    "\uE3D3": "minecraft:repeater",
    "\uE3D4": "minecraft:rotten_flesh",
    "\uE3D5": "minecraft:saddle",
    "\uE3D6": "minecraft:salmon",
    "\uE3D7": "minecraft:salmon_bucket",
    "\uE3D8": "minecraft:sea_pickle",
    "\uE3D9": "minecraft:shears",
    "\uE3DA": "minecraft:shield",
    "\uE3DB": "minecraft:shulker_shell",
    "\uE3DC": "minecraft:slime_ball",
    "\uE3DD": "minecraft:snowball",
    "\uE3DE": "minecraft:spider_eye",
    "\uE3DF": "minecraft:spyglass",
    "\uE3E0": "minecraft:stick",
    "\uE3E1": "minecraft:stone_axe",
    "\uE3E2": "minecraft:stone_hoe",
    "\uE3E3": "minecraft:stone_pickaxe",
    "\uE3E4": "minecraft:stone_shovel",
    "\uE3E5": "minecraft:stone_sword",
    "\uE3E6": "minecraft:string",
    "\uE3E7": "minecraft:sugar",
    "\uE3E8": "minecraft:suspicious_stew",
    "\uE3E9": "minecraft:sweet_berries",
    "\uE3EA": "minecraft:tnt_minecart",
    "\uE3EB": "minecraft:torch",
    "\uE3EC": "minecraft:totem_of_undying",
    "\uE3ED": "minecraft:trident",
    "\uE3EE": "minecraft:tripwire_hook",
    "\uE3EF": "minecraft:tropical_fish",
    "\uE3F0": "minecraft:tropical_fish_bucket",
    "\uE3F1": "minecraft:turtle_egg",
    "\uE3F2": "minecraft:vine",
    "\uE3F3": "minecraft:warped_fungus_on_a_stick",
    "\uE3F4": "minecraft:waterlily",
    "\uE3F5": "minecraft:water_bucket",
    "\uE3F6": "minecraft:wheat",
    "\uE3F7": "minecraft:wheat_seeds",
    "\uE3F8": "minecraft:white_dye",
    "\uE3F9": "minecraft:wooden_axe",
    "\uE3FA": "minecraft:wooden_hoe",
    "\uE3FB": "minecraft:wooden_pickaxe",
    "\uE3FC": "minecraft:wooden_shovel",
    "\uE3FD": "minecraft:wooden_sword",
    "\uE3FE": "minecraft:writable_book",
    "\uE3FF": "minecraft:yellow_dye"
};
