export const cardMarker = '\uE107';
export const emoji_ids = {
    "\uE088": "minecraft:soul_campfire",
    "\uE089": "minecraft:soul_lantern",
    "\uE08A": "minecraft:soul_torch",
    "\uE08B": "minecraft:crimson_fungus",
    "\uE08C": "minecraft:warped_fungus",
    "\uE08D": "minecraft:weeping_vines",
    "\uE08E": "minecraft:twisting_vines",
    
    "\uE090": "minecraft:acacia_boat",
    "\uE091": "minecraft:birch_boat",
    "\uE092": "minecraft:dark_oak_boat",
    "\uE093": "minecraft:jungle_boat",
    "\uE094": "minecraft:oak_boat",
    "\uE095": "minecraft:spruce_boat",

    "\uE096": "minecraft:acacia_door",
    "\uE097": "minecraft:birch_door",
    "\uE098": "minecraft:dark_oak_door",
    "\uE099": "minecraft:jungle_door",
    "\uE09A": "minecraft:wooden_door",
    "\uE09B": "minecraft:spruce_door",
    "\uE09C": "minecraft:iron_door",
    "\uE09D": "minecraft:crimson_door",
    "\uE09E": "minecraft:warped_door",
    
    "\uE0A2": "minecraft:acacia_sign",
    "\uE0A3": "minecraft:birch_sign",
    "\uE0A4": "minecraft:dark_oak_sign",
    "\uE0A5": "minecraft:jungle_sign",
    "\uE0A6": "minecraft:oak_sign",
    "\uE0A7": "minecraft:spruce_sign",
    "\uE0A8": "minecraft:crimson_sign",
    "\uE0A9": "minecraft:warped_sign",

    "\uE0AA": { "id": "minecraft:sapling", "data": 0 },
    "\uE0AB": { "id": "minecraft:sapling", "data": 1 },
    "\uE0AC": { "id": "minecraft:sapling", "data": 2 },
    "\uE0AD": { "id": "minecraft:sapling", "data": 3 },
    "\uE0AE": { "id": "minecraft:sapling", "data": 4 },
    "\uE0AF": { "id": "minecraft:sapling", "data": 5 },

    "\uE0B0": { "id": "minecraft:red_flower", "data": 0 },
    "\uE0B1": { "id": "minecraft:red_flower", "data": 1 },
    "\uE0B2": { "id": "minecraft:red_flower", "data": 2 },
    "\uE0B3": { "id": "minecraft:red_flower", "data": 3 },
    "\uE0B4": { "id": "minecraft:red_flower", "data": 4 },
    "\uE0B5": { "id": "minecraft:red_flower", "data": 5 },
    "\uE0B6": { "id": "minecraft:red_flower", "data": 6 },
    "\uE0B7": { "id": "minecraft:red_flower", "data": 7 },
    "\uE0B8": { "id": "minecraft:red_flower", "data": 8 },
    "\uE0B9": { "id": "minecraft:red_flower", "data": 9 },
    "\uE0BA": { "id": "minecraft:red_flower", "data": 10 },
    "\uE0BB": "minecraft:yellow_flower",
    "\uE0BC": { "id": "minecraft:double_plant", "data": 0 },
    "\uE0BD": { "id": "minecraft:double_plant", "data": 1 },
    "\uE0BE": { "id": "minecraft:double_plant", "data": 4 },
    "\uE0BF": { "id": "minecraft:double_plant", "data": 5 },
    
    "\uE0D0": { "id": "minecraft:bed", "data": 0 },
    "\uE0D1": { "id": "minecraft:bed", "data": 1 },
    "\uE0D2": { "id": "minecraft:bed", "data": 2 },
    "\uE0D3": { "id": "minecraft:bed", "data": 3 },
    "\uE0D4": { "id": "minecraft:bed", "data": 4 },
    "\uE0D5": { "id": "minecraft:bed", "data": 5 },
    "\uE0D6": { "id": "minecraft:bed", "data": 6 },
    "\uE0D7": { "id": "minecraft:bed", "data": 7 },
    "\uE0D8": { "id": "minecraft:bed", "data": 8 },
    "\uE0D9": { "id": "minecraft:bed", "data": 9 },
    "\uE0DA": { "id": "minecraft:bed", "data": 10 },
    "\uE0DB": { "id": "minecraft:bed", "data": 11 },
    "\uE0DC": { "id": "minecraft:bed", "data": 12 },
    "\uE0DD": { "id": "minecraft:bed", "data": 13 },
    "\uE0DE": { "id": "minecraft:bed", "data": 14 },
    "\uE0DF": { "id": "minecraft:bed", "data": 15 },
    
    "\uE0EF": "minecraft:candle",
    "\uE0F0": "minecraft:white_candle",
    "\uE0F1": "minecraft:orange_candle",
    "\uE0F2": "minecraft:magenta_candle",
    "\uE0F3": "minecraft:light_blue_candle",
    "\uE0F4": "minecraft:yellow_candle",
    "\uE0F5": "minecraft:lime_candle",
    "\uE0F6": "minecraft:pink_candle",
    "\uE0F7": "minecraft:gray_candle",
    "\uE0F8": "minecraft:light_gray_candle",
    "\uE0F9": "minecraft:cyan_candle",
    "\uE0FA": "minecraft:purple_candle",
    "\uE0FB": "minecraft:blue_candle",
    "\uE0FC": "minecraft:brown_candle",
    "\uE0FD": "minecraft:green_candle",
    "\uE0FE": "minecraft:red_candle",
    "\uE0FF": "minecraft:black_candle",

    "\uE108": "minecraft:activator_rail",
    "\uE109": "minecraft:amethyst_shard",
    "\uE10A": "minecraft:apple",
    "\uE10B": "minecraft:armor_stand",
    "\uE10C": "minecraft:arrow",
    "\uE10D": "minecraft:axolotl_bucket",
    "\uE10E": "minecraft:baked_potato",
    "\uE10F": "minecraft:bamboo",
    "\uE110": "minecraft:beef",
    "\uE111": "minecraft:beetroot",
    "\uE112": "minecraft:beetroot_seeds",
    "\uE113": "minecraft:beetroot_soup",
    "\uE114": "minecraft:bell",
    "\uE115": "minecraft:black_dye",
    "\uE116": "minecraft:blaze_powder",
    "\uE117": "minecraft:blaze_rod",
    "\uE118": "minecraft:blue_dye",
    "\uE119": "minecraft:bone",
    "\uE11A": "minecraft:bone_meal",
    "\uE11B": "minecraft:book",
    "\uE11C": "minecraft:bow",
    "\uE11D": "minecraft:bowl",
    "\uE11E": "minecraft:bread",
    "\uE11F": "minecraft:brewing_stand",
    "\uE120": "minecraft:brick",
    "\uE121": "minecraft:brown_dye",
    "\uE122": "minecraft:brown_mushroom",
    "\uE123": "minecraft:bucket",
    "\uE124": "minecraft:cake",
    "\uE125": "minecraft:campfire",
    "\uE126": "minecraft:carrot",
    "\uE127": "minecraft:carrot_on_a_stick",
    "\uE128": "minecraft:cauldron",
    "\uE129": "minecraft:chain",
    "\uE12A": "minecraft:chainmail_boots",
    "\uE12B": "minecraft:chainmail_chestplate",
    "\uE12C": "minecraft:chainmail_helmet",
    "\uE12D": "minecraft:chainmail_leggings",
    "\uE12E": "minecraft:charcoal",
    "\uE12F": "minecraft:chest_minecart",
    "\uE130": "minecraft:chicken",
    "\uE131": "minecraft:chorus_fruit",
    "\uE132": "minecraft:clay_ball",
    "\uE133": "minecraft:clock",
    "\uE134": "minecraft:coal",
    "\uE135": "minecraft:cocoa_beans",
    "\uE136": "minecraft:cod",
    "\uE137": "minecraft:cod_bucket",
    "\uE138": "minecraft:comparator",
    "\uE139": "minecraft:compass",
    "\uE13A": "minecraft:cooked_beef",
    "\uE13B": "minecraft:cooked_chicken",
    "\uE13C": "minecraft:cooked_cod",
    "\uE13D": "minecraft:cooked_mutton",
    "\uE13E": "minecraft:cooked_porkchop",
    "\uE13F": "minecraft:cooked_rabbit",
    "\uE140": "minecraft:cooked_salmon",
    "\uE141": "minecraft:cookie",
    "\uE142": "minecraft:copper_ingot",
    "\uE143": "minecraft:crossbow",
    "\uE144": "minecraft:cyan_dye",
    "\uE145": "minecraft:detector_rail",
    "\uE146": "minecraft:diamond",
    "\uE147": "minecraft:diamond_axe",
    "\uE148": "minecraft:diamond_boots",
    "\uE149": "minecraft:diamond_chestplate",
    "\uE14A": "minecraft:diamond_helmet",
    "\uE14B": "minecraft:diamond_hoe",
    "\uE14C": "minecraft:diamond_horse_armor",
    "\uE14D": "minecraft:diamond_leggings",
    "\uE14E": "minecraft:diamond_pickaxe",
    "\uE14F": "minecraft:diamond_shovel",
    "\uE150": "minecraft:diamond_sword",
    "\uE151": "minecraft:dried_kelp",
    "\uE152": "minecraft:egg",
    "\uE153": "minecraft:elytra",
    "\uE154": "minecraft:emerald",
    "\uE155": "minecraft:enchanted_book",
    "\uE156": "minecraft:ender_eye",
    "\uE157": "minecraft:ender_pearl",
    "\uE158": "minecraft:end_crystal",
    "\uE159": "minecraft:experience_bottle",
    "\uE15A": "minecraft:feather",
    "\uE15B": "minecraft:fermented_spider_eye",
    "\uE15C": "minecraft:firework_rocket",
    "\uE15D": "minecraft:fire_charge",
    "\uE15E": "minecraft:fishing_rod",
    "\uE15F": "minecraft:flint",
    "\uE160": "minecraft:flint_and_steel",
    "\uE161": "minecraft:flower_pot",
    "\uE162": "minecraft:frame",
    "\uE163": "minecraft:ghast_tear",
    "\uE164": "minecraft:glass_bottle",
    "\uE165": "minecraft:glistering_melon_slice",
    "\uE166": "minecraft:glowstone_dust",
    "\uE167": "minecraft:glow_berries",
    "\uE168": "minecraft:glow_frame",
    "\uE169": "minecraft:glow_ink_sac",
    "\uE16A": "minecraft:golden_apple",
    "\uE16B": "minecraft:golden_axe",
    "\uE16C": "minecraft:golden_boots",
    "\uE16D": "minecraft:golden_carrot",
    "\uE16E": "minecraft:golden_chestplate",
    "\uE16F": "minecraft:golden_helmet",
    "\uE170": "minecraft:golden_hoe",
    "\uE171": "minecraft:golden_horse_armor",
    "\uE172": "minecraft:golden_leggings",
    "\uE173": "minecraft:golden_pickaxe",
    "\uE174": "minecraft:golden_rail",
    "\uE175": "minecraft:golden_shovel",
    "\uE176": "minecraft:golden_sword",
    "\uE177": "minecraft:gold_ingot",
    "\uE178": "minecraft:gold_nugget",
    "\uE179": "minecraft:gray_dye",
    "\uE17A": "minecraft:green_dye",
    "\uE17B": "minecraft:gunpowder",
    "\uE17C": "minecraft:honeycomb",
    "\uE17D": "minecraft:honey_bottle",
    "\uE17E": "minecraft:hopper",
    "\uE17F": "minecraft:hopper_minecart",
    "\uE180": "minecraft:ink_sac",
    "\uE181": "minecraft:iron_axe",
    "\uE182": "minecraft:iron_boots",
    "\uE183": "minecraft:iron_chestplate",
    "\uE184": "minecraft:iron_helmet",
    "\uE185": "minecraft:iron_hoe",
    "\uE186": "minecraft:iron_horse_armor",
    "\uE187": "minecraft:iron_ingot",
    "\uE188": "minecraft:iron_leggings",
    "\uE189": "minecraft:iron_nugget",
    "\uE18A": "minecraft:iron_pickaxe",
    "\uE18B": "minecraft:iron_shovel",
    "\uE18C": "minecraft:iron_sword",
    "\uE18D": "minecraft:kelp",
    "\uE18E": "minecraft:lantern",
    "\uE18F": "minecraft:lapis_lazuli",
    "\uE190": "minecraft:lava_bucket",
    "\uE191": "minecraft:lead",
    "\uE192": "minecraft:leather",
    "\uE193": "minecraft:leather_boots",
    "\uE194": "minecraft:leather_chestplate",
    "\uE195": "minecraft:leather_helmet",
    "\uE196": "minecraft:leather_horse_armor",
    "\uE197": "minecraft:leather_leggings",
    "\uE198": "minecraft:lever",
    "\uE199": "minecraft:light_blue_dye",
    "\uE19A": "minecraft:light_gray_dye",
    "\uE19B": "minecraft:lime_dye",
    "\uE19C": "minecraft:magenta_dye",
    "\uE19D": "minecraft:magma_cream",
    "\uE19E": "minecraft:melon_seeds",
    "\uE19F": "minecraft:melon_slice",
    "\uE1A0": "minecraft:milk_bucket",
    "\uE1A1": "minecraft:minecart",
    "\uE1A2": "minecraft:mushroom_stew",
    "\uE1A3": "minecraft:mutton",
    "\uE1A4": "minecraft:name_tag",
    "\uE1A5": "minecraft:nautilus_shell",
    "\uE1A6": "minecraft:netherbrick",
    "\uE1A7": "minecraft:netherite_axe",
    "\uE1A8": "minecraft:netherite_boots",
    "\uE1A9": "minecraft:netherite_chestplate",
    "\uE1AA": "minecraft:netherite_helmet",
    "\uE1AB": "minecraft:netherite_hoe",
    "\uE1AC": "minecraft:netherite_ingot",
    "\uE1AD": "minecraft:netherite_leggings",
    "\uE1AE": "minecraft:netherite_pickaxe",
    "\uE1AF": "minecraft:netherite_scrap",
    "\uE1B0": "minecraft:netherite_shovel",
    "\uE1B1": "minecraft:netherite_sword",
    "\uE1B2": "minecraft:nether_wart",
    "\uE1B3": "minecraft:orange_dye",
    "\uE1B4": "minecraft:painting",
    "\uE1B5": "minecraft:paper",
    "\uE1B6": "minecraft:phantom_membrane",
    "\uE1B7": "minecraft:pink_dye",
    "\uE1B8": "minecraft:pointed_dripstone",
    "\uE1B9": "minecraft:poisonous_potato",
    "\uE1BA": "minecraft:popped_chorus_fruit",
    "\uE1BB": "minecraft:porkchop",
    "\uE1BC": "minecraft:potato",
    "\uE1BD": "minecraft:powder_snow_bucket",
    "\uE1BE": "minecraft:prismarine_crystals",
    "\uE1BF": "minecraft:prismarine_shard",
    "\uE1C0": "minecraft:pufferfish",
    "\uE1C1": "minecraft:pufferfish_bucket",
    "\uE1C2": "minecraft:pumpkin_pie",
    "\uE1C3": "minecraft:pumpkin_seeds",
    "\uE1C4": "minecraft:purple_dye",
    "\uE1C5": "minecraft:quartz",
    "\uE1C6": "minecraft:rabbit",
    "\uE1C7": "minecraft:rabbit_foot",
    "\uE1C8": "minecraft:rabbit_hide",
    "\uE1C9": "minecraft:rabbit_stew",
    "\uE1CA": "minecraft:rail",
    "\uE1CB": "minecraft:raw_copper",
    "\uE1CC": "minecraft:raw_gold",
    "\uE1CD": "minecraft:raw_iron",
    "\uE1CE": "minecraft:redstone",
    "\uE1CF": "minecraft:redstone_torch",
    "\uE1D0": "minecraft:red_dye",
    "\uE1D1": "minecraft:red_mushroom",
    "\uE1D2": "minecraft:sugar_cane",
    "\uE1D3": "minecraft:repeater",
    "\uE1D4": "minecraft:rotten_flesh",
    "\uE1D5": "minecraft:saddle",
    "\uE1D6": "minecraft:salmon",
    "\uE1D7": "minecraft:salmon_bucket",
    "\uE1D8": "minecraft:sea_pickle",
    "\uE1D9": "minecraft:shears",
    "\uE1DA": "minecraft:shield",
    "\uE1DB": "minecraft:shulker_shell",
    "\uE1DC": "minecraft:slime_ball",
    "\uE1DD": "minecraft:snowball",
    "\uE1DE": "minecraft:spider_eye",
    "\uE1DF": "minecraft:spyglass",
    "\uE1E0": "minecraft:stick",
    "\uE1E1": "minecraft:stone_axe",
    "\uE1E2": "minecraft:stone_hoe",
    "\uE1E3": "minecraft:stone_pickaxe",
    "\uE1E4": "minecraft:stone_shovel",
    "\uE1E5": "minecraft:stone_sword",
    "\uE1E6": "minecraft:string",
    "\uE1E7": "minecraft:sugar",
    "\uE1E8": "minecraft:suspicious_stew",
    "\uE1E9": "minecraft:sweet_berries",
    "\uE1EA": "minecraft:tnt_minecart",
    "\uE1EB": "minecraft:torch",
    "\uE1EC": "minecraft:totem_of_undying",
    "\uE1ED": "minecraft:trident",
    "\uE1EE": "minecraft:tripwire_hook",
    "\uE1EF": "minecraft:tropical_fish",
    "\uE1F0": "minecraft:tropical_fish_bucket",
    "\uE1F1": "minecraft:turtle_egg",
    "\uE1F2": "minecraft:vine",
    "\uE1F3": "minecraft:warped_fungus_on_a_stick",
    "\uE1F4": "minecraft:waterlily",
    "\uE1F5": "minecraft:water_bucket",
    "\uE1F6": "minecraft:wheat",
    "\uE1F7": "minecraft:wheat_seeds",
    "\uE1F8": "minecraft:white_dye",
    "\uE1F9": "minecraft:wooden_axe",
    "\uE1FA": "minecraft:wooden_hoe",
    "\uE1FB": "minecraft:wooden_pickaxe",
    "\uE1FC": "minecraft:wooden_shovel",
    "\uE1FD": "minecraft:wooden_sword",
    "\uE1FE": "minecraft:writable_book",
    "\uE1FF": "minecraft:yellow_dye"
}
